sudo: required
language: scala
scala:
  - 2.11.8
branches:
  only:
    - dev
    - master
services:
  - docker
notifications:
  email:
    recipients:
      - ernest@unstable.build
script: scripts/test.sh
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push ernestrc/sonicd:`git rev-parse --short HEAD`;
    docker push ernestrc/sonicd:latest;
