sudo: required
language: scala
scala:
  - 2.11.8
branches:
  only:
    - dev
    - master
services:
  - docker
notifications:
  email:
    recipients:
      - ernest@unstable.build
script: scripts/test.sh
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push xarxa6/sonicd:`git rev-parse --short HEAD`;
