[package]
name = "sonicd"
version = "0.4.4"
authors = ["Ernest Romero <ernest@unstable.build>"]

[lib]
name = "libsonicd"
path = "lib/rust/src/lib.rs"

[[bin]]
name = "sonic"
path = "cli/src/main.rs"

[[bin]]
name = "sonicc"
path = "cache/src/main.rs"

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
byteorder = "*"
curl = "*"
nix = "*"
log = "*"

# cli
regex = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
env_logger = "*"
pbr = "*"

# cache
threadpool = "*"
num_cpus = "0.2"
ws = "*"
lazy_static = "0.1.*"

#[profile.release]
#debug = true
