[package]
name = "sonicd"
version = "0.5.0"
authors = ["Ernest Romero <ernest@unstable.build>"]

[lib]
name = "sonicd"
path = "lib/rust/src/lib.rs"


[features]
# FIXME https://github.com/rust-lang/cargo/pull/2325
# individual Cargo.toml are used for now
# cache = ["threadpool", "num_cpus", "ws", "lazy_static", "env_logger"]
# cli = ["regex", "docopt", "docopt_macros", "rustc-serialize", "env_logger", "pbr"]
websocket = ["ws"]

# [[bin]]
# name = "sonic"
# path = "cli/src/main.rs"
# features = ["cli"]

# [[bin]]
# name = "sonicc"
# path = "cache/src/main.rs"
# features = ["cache"]

# cli
# regex ={ version = "*", optional = true }
# docopt ={ version = "*", optional = true }
# docopt_macros ={ version = "*", optional = true }
# rustc-serialize ={ version = "*", optional = true }
# pbr = { version = "*", optional = true }

# cache
# threadpool = { version = "*", optional = true }
# num_cpus = { version = "0.2", optional = true }
# lazy_static = { version =  "0.1.*", optional = true }

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
byteorder = "*"
curl = "*"
nix = "*"
log = "*"

ws = { version =  "*", optional = true }
